"""Build PHASE_C_ALL_VERDICTS.json from evaluation session data.

Extracts all 76 per-book verdicts from Sessions 0-7 into a single structured JSON.
All values sourced from session reports (PHASE_C_ERRATA.md §12, SESSION1-7_REPORT.md).
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

verdicts = [
    # ══════════════════════════════════════════════════════════════
    # SESSION 0 — Calibration (3 books) — from PHASE_C_ERRATA.md §12
    # ══════════════════════════════════════════════════════════════
    {
        "book": "أحكام الاضطباع والرمل في الطواف",
        "session": 0,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "عبد الله بن إبراهيم الزاحم",
        "author_correct": True,
        "author_confidence_opus": 0.72,
        "death_date": None,
        "death_source": "absent",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.88,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "Modern obscure author, only 1 independent source",
        "duplicate_of": None,
    },
    {
        "book": "الأربعون النووية",
        "session": 0,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو زكريا محيي الدين يحيى بن شرف النووي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 676,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith", "fiqh", "aqidah", "tasawwuf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Gate abort: author-science mismatch; Opus science superset broad",
        "duplicate_of": "S3 Book 7",
    },
    {
        "book": "مجموع الفتاوى",
        "session": 0,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد بن عبد الحليم بن عبد السلام ابن تيمية الحراني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 728,
        "death_source": "genuine-inference",
        "genre": "fatawa",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah", "fiqh", "usul_al_fiqh", "tafsir", "hadith", "tasawwuf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Death 728 genuine inference correct; compiler/author distinction passed",
        "duplicate_of": "S3 Book 6",
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 1 — Fixture Regression (11 new books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "مذكرات مالك بن نبي - العفن",
        "session": 1,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "مالك بن الحاج عمر بن الخضر بن نبي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 1393,
        "death_source": "pass-through",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tarikh", "fikr_islami"],
        "trust_tier": "flagged",
        "trust_score": 0.6075,
        "consensus_agreed": True,
        "key_issues": "Modern non-Islamic memoirs; GT all_match except level",
        "duplicate_of": None,
    },
    {
        "book": "أساليب بلاغية",
        "session": 1,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد مطلوب أحمد الناصري الصيادي الرفاعي",
        "author_correct": True,
        "author_confidence_opus": 0.95,
        "death_date": 1432,
        "death_source": "genuine-inference",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.72,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["balagha"],
        "trust_tier": "flagged",
        "trust_score": 0.54,
        "consensus_agreed": True,
        "key_issues": "Death date 1432 genuine inference WRONG (actual 1439, 7-year gap)",
        "duplicate_of": None,
    },
    {
        "book": "أسلوب خطبة الجمعة",
        "session": 1,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "عبد الله بن ضيف الله الرحيلي",
        "author_correct": True,
        "author_confidence_opus": 0.70,
        "death_date": None,
        "death_source": "absent",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh", "adab"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "Obscure modern author, low conf (0.70); result.json carries CA values",
        "duplicate_of": None,
    },
    {
        "book": "البدر التمام بما صح من أدلة الأحكام",
        "session": 1,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو خلاد ناصر بن سعيد بن سيف السيف",
        "author_correct": True,
        "author_confidence_opus": 0.82,
        "death_date": None,
        "death_source": "absent",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "fiqh"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "Very obscure modern compiler; correct disambiguation from classical homonym",
        "duplicate_of": None,
    },
    {
        "book": "آداب الصحبة لأبي عبد الرحمن السلمي",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد بن الحسين بن محمد بن موسى بن خالد بن سالم النيسابوري، أبو عبد الرحمن السلمي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 412,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tasawwuf", "adab"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Gate abort: author-science mismatch; Opus attribution=traditional vs GT definitive",
        "duplicate_of": None,
    },
    {
        "book": "آداب الفتوى والمفتي والمستفتي",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو زكريا محيي الدين يحيى بن شرف النووي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 676,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Extracted from مقدمة المجموع شرح المهذب",
        "duplicate_of": None,
    },
    {
        "book": "أبنية الأسماء والأفعال والمصادر",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "VERIFIED",
        "author_name": "علي بن جعفر بن علي السعدي الصقلي، أبو القاسم ابن القطاع",
        "author_correct": True,
        "author_confidence_opus": 0.96,
        "death_date": 515,
        "death_source": "pass-through",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.88,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["sarf", "lughah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": False,
        "key_issues": "Consensus DISAGREED; GPT-5.4 misspelled author (ابن القطان vs ابن القطاع)",
        "duplicate_of": None,
    },
    {
        "book": "أحاديث أيوب السختيانى",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "القاضي أبو إسحاق إسماعيل بن إسحاق بن إسماعيل بن حماد بن زيد الأزدي البصري ثم البغدادي المالكي الجهضمي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 282,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "GT title mismatch (BUG-C05); attribution Opus=traditional vs GT=definitive",
        "duplicate_of": None,
    },
    {
        "book": "أنوار الهلالين في التعقبات على الجلالين",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "PLAUSIBLE",
        "author_name": "محمد بن عبد الرحمن الخميس",
        "author_correct": True,
        "author_confidence_opus": 0.82,
        "death_date": None,
        "death_source": "absent",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tafsir", "aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Modern living academic; تعقبات genre not in enum; GT says risalah",
        "duplicate_of": None,
    },
    {
        "book": "أخبار أبي القاسم الزجاجي",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "عبد الرحمن بن إسحاق البغدادي النهاوندي الزجاجي، أبو القاسم",
        "author_correct": True,
        "author_confidence_opus": 0.95,
        "death_date": 337,
        "death_source": "pass-through",
        "genre": "adab",
        "genre_correct": True,
        "genre_confidence_opus": 0.75,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab", "nahw", "lughah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Attribution both=traditional vs GT=definitive",
        "duplicate_of": None,
    },
    {
        "book": "همع الهوامع في شرح جمع الجوامع",
        "session": 1,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "عبد الرحمن بن أبي بكر بن محمد جلال الدين السيوطي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 911,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["nahw", "sarf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Self-commentary (same author for matn and sharh); academic journal confirms",
        "duplicate_of": None,
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 2 — Famous Works A (8 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "حاشية ابن عابدين = رد المحتار - ط الحلبي",
        "session": 2,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد أمين بن عمر بن عبد العزيز عابدين الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 1252,
        "death_source": "false-positive",
        "genre": "hashiyah",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "3-layer chain verified; death date from raw text not inference; Opus layer detail superior",
        "duplicate_of": "S6 Book 16",
    },
    {
        "book": "لسان العرب",
        "session": 2,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد بن مكرم بن علي، أبو الفضل، جمال الدين ابن منظور الأنصاري الرويفعي الإفريقي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 711,
        "death_source": "pass-through",
        "genre": "mujam",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["lughah"],
        "trust_tier": "verified",
        "trust_score": 0.655,
        "consensus_agreed": True,
        "key_issues": "Textbook case; all fields correct",
        "duplicate_of": None,
    },
    {
        "book": "سير أعلام النبلاء - ط الحديث",
        "session": 2,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "شمس الدين محمد بن أحمد بن عثمان الذهبي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 748,
        "death_source": "pass-through",
        "genre": "tabaqat",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tarikh", "sirah"],
        "trust_tier": "verified",
        "trust_score": 0.7175,
        "consensus_agreed": True,
        "key_issues": "CA sirah technically imprecise for biographical dictionary; result.json carries CA values",
        "duplicate_of": None,
    },
    {
        "book": "فتح الباري بشرح البخاري - ط السلفية",
        "session": 2,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد بن علي بن محمد بن محمد بن علي بن حجر العسقلاني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 852,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "CRITICAL CHECK PASSED: author=ابن حجر not البخاري; tahqiq_note on genuine sharh (not flagged)",
        "duplicate_of": None,
    },
    {
        "book": "بداية المجتهد ونهاية المقتصد",
        "session": 2,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو الوليد محمد بن أحمد بن محمد بن أحمد بن رشد القرطبي الأندلسي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 595,
        "death_source": "false-positive",
        "genre": "fiqh_comparative",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh", "usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "ابن رشد الحفيد (not الجد) correctly identified; death date from raw text",
        "duplicate_of": None,
    },
    {
        "book": "الموسوعة الفقهية الكويتية",
        "session": 2,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "وزارة الأوقاف والشئون الإسلامية - الكويت",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": None,
        "death_source": "absent",
        "genre": "mawsuah",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": "flagged",
        "trust_score": 0.4625,
        "consensus_agreed": True,
        "key_issues": "Institutional author from EMPTY author_raw; trust=flagged despite high authority",
        "duplicate_of": None,
    },
    {
        "book": "مسند أحمد - ت شاكر - ط دار الحديث",
        "session": 2,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد بن محمد بن حنبل الشيباني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 241,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": True,
        "ml_correct": False,
        "ml_disagreement": True,
        "science_scope": ["hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Tahqiq-as-layer bias: Opus ML=true (wrong, conf 0.90), CA=false; consensus agreed despite ML disagreement",
        "duplicate_of": None,
    },
    {
        "book": "زاد المستقنع في اختصار المقنع - ت العسكر",
        "session": 2,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "موسى بن أحمد بن موسى بن سالم الحجاوي المقدسي الصالحي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 968,
        "death_source": "pass-through",
        "genre": "mukhtasar",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Death date scholarly dispute (960 vs 968); pipeline has 968 (majority view)",
        "duplicate_of": None,
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 3 — Famous Works B (7 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "الرحيق المختوم",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "صفي الرحمن المباركفوري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 1427,
        "death_source": "false-positive",
        "genre": "sirah",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["sirah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Death date from raw text (false-positive, not genuine inference)",
        "duplicate_of": None,
    },
    {
        "book": "الأم للشافعي - ط الفكر",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو عبد الله محمد بن إدريس بن العباس الشافعي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 204,
        "death_source": "pass-through",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "matn imprecise for 8-volume work; attribution Opus=traditional (complex transmission)",
        "duplicate_of": None,
    },
    {
        "book": "الرسالة للشافعي",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد بن إدريس بن العباس بن عثمان بن شافع الشافعي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 204,
        "death_source": "false-positive",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": True,
        "ml_correct": False,
        "ml_disagreement": True,
        "science_scope": ["usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Tahqiq-as-layer bias: Opus ML=true (wrong, conf 0.85), CA=false; death date from raw text",
        "duplicate_of": None,
    },
    {
        "book": "الأذكار للنووي ت الأرنؤوط",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "VERIFIED",
        "author_name": "أبو زكريا محيي الدين يحيى بن شرف النووي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 676,
        "death_source": "pass-through",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "tasawwuf", "adab"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Genre imprecise (thematic compilation); Opus=matn GPT=hadith_collection, neither precise",
        "duplicate_of": None,
    },
    {
        "book": "شرح النووي على مسلم",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو زكريا محيي الدين يحيى بن شرف بن مري بن حسن بن حسين بن حزام النووي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 676,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Genuine sharh; layer chain verified (matn=مسلم, sharh=النووي)",
        "duplicate_of": None,
    },
    {
        "book": "مجموع الفتاوى",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد بن عبد الحليم بن عبد السلام ابن تيمية الحراني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 728,
        "death_source": "genuine-inference",
        "genre": "fatawa",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah", "fiqh", "usul_al_fiqh", "tafsir", "hadith", "tasawwuf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "REGRESSION: consistent with S0; death 728 genuine inference correct",
        "duplicate_of": "S0 Book 3",
    },
    {
        "book": "الأربعون النووية",
        "session": 3,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو زكريا محيي الدين يحيى بن شرف النووي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 676,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith", "fiqh", "aqidah", "tasawwuf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "REGRESSION: identical to S0 on every dimension; zero divergence",
        "duplicate_of": "S0 Book 2",
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 4 — Multi-Layer + Commentary (10 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "فتح الباري لابن رجب",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "زين الدين عبد الرحمن بن أحمد بن رجب الحنبلي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 795,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith", "aqidah", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Correctly distinguished from ابن حجر's فتح الباري (Session 2)",
        "duplicate_of": None,
    },
    {
        "book": "شرح الورقات في أصول الفقه - المحلي",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "جلال الدين محمد بن أحمد المحلي الشافعي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 864,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "المحلي consistent across Books 2-3 in session",
        "duplicate_of": None,
    },
    {
        "book": "حاشية العطار على شرح الجلال المحلي على جمع الجوامع",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "VERIFIED",
        "author_name": "حسن بن محمد بن محمود العطار",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 1250,
        "death_source": "pass-through",
        "genre": "hashiyah",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Only genuine hashiyah in S4; 3 distinct layers verified; GPT-5.4 comparable to CA",
        "duplicate_of": None,
    },
    {
        "book": "شرح العقيدة الطحاوية - ط الرسالة",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "علي بن أبي العز الحنفي الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 792,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Attribution Opus=traditional, CA=definitive (scholarly discussion exists)",
        "duplicate_of": "S6 Book 15",
    },
    {
        "book": "مقامات الحريري",
        "session": 4,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو محمد القاسم بن علي الحريري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 516,
        "death_source": "pass-through",
        "genre": "adab",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab"],
        "trust_tier": "verified",
        "trust_score": 0.6925,
        "consensus_agreed": True,
        "key_issues": "Matn for شرح مقامات الحريري (Session 4 Book 6)",
        "duplicate_of": None,
    },
    {
        "book": "شرح مقامات الحريري",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو العباس أحمد بن عبد المؤمن الشريشي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 619,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab", "lughah", "balagha"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Matn author matches مقامات الحريري; CA conf 0.90 lower for less famous sharh author",
        "duplicate_of": None,
    },
    {
        "book": "شرح ديوان المتنبي للواحدي",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "الواحدي النيسابوري",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 468,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab", "balagha", "lughah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "المتنبي cluster — shared matn author with Book 8",
        "duplicate_of": None,
    },
    {
        "book": "اللامع العزيزي شرح ديوان المتنبي",
        "session": 4,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو العلاء المعري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 449,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab", "lughah", "nahw", "balagha"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "No tahqiq_note despite muhaqiq — adds to necessary-but-not-sufficient finding",
        "duplicate_of": None,
    },
    {
        "book": "المآخذ على شراح ديوان أبي الطيب المتنبي",
        "session": 4,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أحمد بن علي بن معقل الأزدي المهلبي",
        "author_correct": True,
        "author_confidence_opus": 0.88,
        "death_date": 644,
        "death_source": "pass-through",
        "genre": "adab",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab"],
        "trust_tier": "verified",
        "trust_score": 0.7175,
        "consensus_agreed": True,
        "key_issues": "CRITICAL CHECK PASSED: NOT sharh (literary criticism OF commentators); Opus genre=other (0.82), result.json=adab (CA)",
        "duplicate_of": None,
    },
    {
        "book": "التعليق على الرحيق المختوم",
        "session": 4,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "محمود بن محمد الملاح",
        "author_correct": True,
        "author_confidence_opus": 0.72,
        "death_date": None,
        "death_source": "absent",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["sirah"],
        "trust_tier": "flagged",
        "trust_score": 0.4625,
        "consensus_agreed": True,
        "key_issues": "Opus hashiyah wrong (0.82, only 2 layers); result.json has CA sharh (correct); matn author matches S3 الرحيق المختوم",
        "duplicate_of": None,
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 5 — Attribution + Trust + Obscure (10 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "الفقه الأكبر",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو حنيفة النعمان بن ثابت بن زوطى",
        "author_correct": True,
        "author_confidence_opus": 0.90,
        "death_date": 150,
        "death_source": "pass-through",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Attribution genuinely disputed; Opus=disputed (correct), CA=traditional",
        "duplicate_of": None,
    },
    {
        "book": "الإبانة عن أصول الديانة - ت العصيمي",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو الحسن علي بن إسماعيل الأشعري",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 324,
        "death_source": "genuine-inference",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Death 324 genuine inference CORRECT; text integrity debated (not authorship); cross-edition genre inconsistency with ت فوقية",
        "duplicate_of": None,
    },
    {
        "book": "الإبانة عن أصول الديانة - ت فوقية",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو الحسن علي بن إسماعيل بن إسحاق بن سالم بن إسماعيل بن عبد الله بن موسى بن أبي بردة بن أبي موسى الأشعري",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 324,
        "death_source": "pass-through",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Same work as ت العصيمي; genre=matn here vs risalah there (cross-edition inconsistency)",
        "duplicate_of": None,
    },
    {
        "book": "البيان والتبيين",
        "session": 5,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "عمرو بن بحر بن محبوب الكناني بالولاء، الليثي، أبو عثمان، الشهير بالجاحظ",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 255,
        "death_source": "pass-through",
        "genre": "adab",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["adab", "lughah"],
        "trust_tier": "verified",
        "trust_score": 0.6925,
        "consensus_agreed": True,
        "key_issues": "Straightforward; one of 4 pillars of Arabic adab",
        "duplicate_of": None,
    },
    {
        "book": "الورقة النحوية",
        "session": 5,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "حازم خنفر",
        "author_correct": True,
        "author_confidence_opus": 0.55,
        "death_date": None,
        "death_source": "absent",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["nahw", "sarf"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "Lowest author conf in corpus (0.55); well-calibrated for modern obscure; 2 pages content_minimal",
        "duplicate_of": None,
    },
    {
        "book": "حديث الضب الذي تكلم بين يدي النبي للطبراني",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "سليمان بن أحمد بن أيوب بن مطير اللخمي الشامي، أبو القاسم الطبراني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 360,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "1 page content_minimal; only Shamela-ecosystem sources",
        "duplicate_of": None,
    },
    {
        "book": "نصيحة لطالب الحق - ضمن «آثار المعلمي»",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "عبد الرحمن بن يحيى المعلمي اليماني",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 1386,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["ulum_al_hadith", "usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "2 pages content_minimal; only Shamela-ecosystem sources for this specific risalah",
        "duplicate_of": None,
    },
    {
        "book": "أدب النفوس للآجري",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو بكر محمد بن الحسين بن عبد الله الآجُرِّيّ البغدادي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 360,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.88,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tasawwuf", "aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Severely truncated (24/271 pages = 9%); only Shamela-ecosystem sources",
        "duplicate_of": None,
    },
    {
        "book": "أحاديث العطار عن شيوخه",
        "session": 5,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد بن الحسن بن يعقوب بن الحسن بن مِقْسَم العطار, أبو بكر",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": 354,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "VERIFY-author passed; multiple independent biographical sources confirm; severely truncated (4%)",
        "duplicate_of": None,
    },
    {
        "book": "الكلام على حديث الإستلقاء لأبي موسى المديني",
        "session": 5,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد بن عمر بن أحمد بن عمر بن محمد الأصبهاني المديني، أبو موسى",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": 581,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": "verified",
        "trust_score": 0.6925,
        "consensus_agreed": True,
        "key_issues": "Result.json carries Opus attribution=traditional (not CA definitive); 2 pages content_minimal",
        "duplicate_of": None,
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 6 — Edition Groups (17 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "أعلام الموقعين عن رب العالمين - ط عطاءات العلم",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن قيم الجوزية",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 751,
        "death_source": "false-positive",
        "genre": "matn",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": False,
        "key_issues": "Genre disagreement Opus=matn vs CA=usul_al_fiqh; ML=false critical check passed; death from raw text",
        "duplicate_of": None,
    },
    {
        "book": "إعلام الموقعين عن رب العالمين - ت مشهور",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن قيم الجوزية",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 751,
        "death_source": "pass-through",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.75,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": False,
        "key_issues": "Consensus disagreed (name format only); lowest genre conf in إعلام group (0.75)",
        "duplicate_of": None,
    },
    {
        "book": "إعلام الموقعين عن رب العالمين - ط العلمية",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن قيم الجوزية",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 751,
        "death_source": "pass-through",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.75,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["usul_al_fiqh", "fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Genre Opus=other vs CA=matn; consensus agreed despite genre difference",
        "duplicate_of": None,
    },
    {
        "book": "البداية والنهاية - ت التركي",
        "session": 6,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "إسماعيل بن عمر بن كثير القرشي الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 774,
        "death_source": "pass-through",
        "genre": "tarikh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tarikh"],
        "trust_tier": "verified",
        "trust_score": 0.8175,
        "consensus_agreed": True,
        "key_issues": "CRITICAL CHECK: tarikh not tafsir; highest trust score in S6 (0.8175)",
        "duplicate_of": None,
    },
    {
        "book": "البداية والنهاية - ط السعادة",
        "session": 6,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "إسماعيل بن عمر بن كثير القرشي الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 774,
        "death_source": "pass-through",
        "genre": "tarikh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tarikh"],
        "trust_tier": "verified",
        "trust_score": 0.6925,
        "consensus_agreed": True,
        "key_issues": "Fully consistent with ت التركي edition; lower trust (missing muhaqiq/publisher)",
        "duplicate_of": None,
    },
    {
        "book": "تفسير الطبري جامع البيان - ت التركي",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو جعفر محمد بن جرير الطبري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 310,
        "death_source": "pass-through",
        "genre": "tafsir",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tafsir", "hadith", "ulum_al_quran"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Clean; both models agree on all fields",
        "duplicate_of": None,
    },
    {
        "book": "تفسير الطبري جامع البيان - ط دار التربية والتراث",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "VERIFIED",
        "author_name": "أبو جعفر محمد بن جرير الطبري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 310,
        "death_source": "pass-through",
        "genre": "tafsir",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": True,
        "science_scope": ["tafsir", "hadith", "ulum_al_quran", "nahw", "lughah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "ML disagreement: Opus=false (correct), GPT-5.4=true (tahqiq_note pattern instance #4)",
        "duplicate_of": None,
    },
    {
        "book": "تحفة المودود بأحكام المولود - ت الأرنؤوط",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن قيم الجوزية",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 751,
        "death_source": "pass-through",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh", "hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Clean; risalah for topical fiqh treatise",
        "duplicate_of": None,
    },
    {
        "book": "تحفة المودود بأحكام المولود - ط عطاءات العلم",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن قيم الجوزية",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 751,
        "death_source": "false-positive",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": False,
        "key_issues": "Consensus disagreed (name format only); death date false-positive (dates in raw text)",
        "duplicate_of": None,
    },
    {
        "book": "فتاوى اللجنة الدائمة - المجموعة الأولى",
        "session": 6,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "اللجنة الدائمة للبحوث العلمية والإفتاء",
        "author_correct": True,
        "author_confidence_opus": 0.98,
        "death_date": None,
        "death_source": "absent",
        "genre": "fatawa",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah", "fiqh"],
        "trust_tier": "flagged",
        "trust_score": 0.4625,
        "consensus_agreed": True,
        "key_issues": "Institutional author; trust=flagged despite high authority",
        "duplicate_of": None,
    },
    {
        "book": "فتاوى اللجنة الدائمة - المجموعة الثانية",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "اللجنة الدائمة للبحوث العلمية والإفتاء",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": None,
        "death_source": "absent",
        "genre": "fatawa",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh", "aqidah", "tafsir", "usul_al_fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Broader science scope than المجموعة الأولى (correct — different topic range)",
        "duplicate_of": None,
    },
    {
        "book": "ألفية ابن مالك - ت القاسم",
        "session": 6,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن مالك الأندلسي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 672,
        "death_source": "pass-through",
        "genre": "nazm",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["nahw", "sarf"],
        "trust_tier": "verified",
        "trust_score": 0.7175,
        "consensus_agreed": True,
        "key_issues": "nazm (versified text) more precise than matn; 1002 verses",
        "duplicate_of": None,
    },
    {
        "book": "ألفية ابن مالك - ط التعاون",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "ابن مالك الأندلسي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 672,
        "death_source": "pass-through",
        "genre": "nazm",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["nahw", "sarf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Identical classification to ت القاسم",
        "duplicate_of": None,
    },
    {
        "book": "شرح العقيدة الطحاوية - ط الأوقاف السعودية",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "صدر الدين علي بن علي بن محمد بن أبي العز الحنفي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 792,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Matches S4 ط الرسالة verdict on all fields",
        "duplicate_of": None,
    },
    {
        "book": "شرح العقيدة الطحاوية - ط الرسالة",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "علي بن علي بن محمد بن أبي العز الحنفي الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 792,
        "death_source": "pass-through",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Re-used from S4; included for cross-edition comparison",
        "duplicate_of": "S4 Book 4",
    },
    {
        "book": "حاشية ابن عابدين = رد المحتار - ط الحلبي",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد أمين بن عمر بن عبد العزيز عابدين الدمشقي",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 1252,
        "death_source": "false-positive",
        "genre": "hashiyah",
        "genre_correct": True,
        "genre_confidence_opus": 0.99,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "FATHER (ت 1252) correctly identified; re-evaluated for father/son cross-check with تكملة",
        "duplicate_of": "S2 Book 1",
    },
    {
        "book": "تكملة حاشية ابن عابدين = قرة عيون الأخيار تكملة رد المحتار - ط الفكر",
        "session": 6,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "محمد علاء الدين بن محمد أمين عابدين",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": 1306,
        "death_source": "genuine-inference",
        "genre": "hashiyah",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["fiqh"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": False,
        "key_issues": "SON (ت 1306) correctly identified; death 1306 genuine inference CORRECT; EMPTY author_raw; consensus disagreed (substantive: death date)",
        "duplicate_of": None,
    },
    # ══════════════════════════════════════════════════════════════
    # SESSION 7 — Remaining (10 books)
    # ══════════════════════════════════════════════════════════════
    {
        "book": "الأحاديث الأربعين النووية مع ما زاد عليها ابن رجب وعليها الشرح الموجز المفيد",
        "session": 7,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "عبد الله بن صالح المحسن",
        "author_correct": True,
        "author_confidence_opus": 0.82,
        "death_date": None,
        "death_source": "absent",
        "genre": "sharh",
        "genre_correct": True,
        "genre_confidence_opus": 0.95,
        "is_multi_layer": True,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "Modern obscure author; independent sources limited to catalogs",
        "duplicate_of": None,
    },
    {
        "book": "الإبدال في لغات الأزد دراسة صوتية في ضوء علم اللغة الحديث",
        "session": 7,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أحمد بن سعيد قشاش",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": None,
        "death_source": "absent",
        "genre": "risalah",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["lughah", "sarf"],
        "trust_tier": "flagged",
        "trust_score": 0.455,
        "consensus_agreed": True,
        "key_issues": "Page mismatch (73/494 = 15%); independent sources limited to catalogs",
        "duplicate_of": None,
    },
    {
        "book": "المستدرك على مجموع الفتاوى",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + gpt_5_4",
        "verdict": "VERIFIED",
        "author_name": "تقي الدين أبو العباس أحمد بن عبد الحليم بن عبد السلام بن تيمية الحراني",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 728,
        "death_source": "pass-through",
        "genre": "fatawa",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["aqidah", "fiqh", "usul_al_fiqh", "tafsir", "hadith", "tasawwuf"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "CRITICAL CHECK: author=ابن تيمية not compiler; consistent with S0 مجموع الفتاوى; GPT-5.4 clean",
        "duplicate_of": None,
    },
    {
        "book": "النكت على شرح النووي على صحيح مسلم",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "هاني فقيه",
        "author_correct": True,
        "author_confidence_opus": 0.75,
        "death_date": None,
        "death_source": "absent",
        "genre": "other",
        "genre_correct": True,
        "genre_confidence_opus": 0.82,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Lowest author conf in corpus (0.75); CA hashiyah=wrong (0.90) causes gate error; nukat genre not in enum",
        "duplicate_of": None,
    },
    {
        "book": "معالم بيانية في آيات قرآنية",
        "session": 7,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "صالح بن عوّاد بن صالح المغامسي",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": None,
        "death_source": "absent",
        "genre": "tafsir",
        "genre_correct": True,
        "genre_confidence_opus": 0.88,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["tafsir", "balagha", "ulum_al_quran"],
        "trust_tier": "flagged",
        "trust_score": 0.4325,
        "consensus_agreed": True,
        "key_issues": "NOT a written book (lecture transcription); 2 pages content_minimal",
        "duplicate_of": None,
    },
    {
        "book": "تاريخ ابن معين - رواية الدارمي",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "يحيى بن معين بن عون بن زياد بن بسطام المري البغدادي",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 233,
        "death_source": "pass-through",
        "genre": "tabaqat",
        "genre_correct": True,
        "genre_confidence_opus": 0.85,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["ulum_al_hadith", "al_jarh_wa_al_tadil"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Famous rijal work; Wikisource full text; tabaqat closest label for jarh wa tadil",
        "duplicate_of": None,
    },
    {
        "book": "حديث يحيى بن معين رواية أبي منصور الشيباني",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "أبو زكريا يحيى بن معين بن عون بن زياد بن بسطام بن عبد الرحمن",
        "author_correct": True,
        "author_confidence_opus": 0.97,
        "death_date": 233,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Minor hadith juz'; no independent web source; same author as تاريخ ابن معين",
        "duplicate_of": None,
    },
    {
        "book": "مسند أبي حنيفة رواية الحصكفي",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "أبو حنيفة النعمان بن ثابت بن زوطي بن ماه",
        "author_correct": True,
        "author_confidence_opus": 0.92,
        "death_date": 150,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.90,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith", "ulum_al_hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Author=أبو حنيفة (narrator) not الحصكفي (compiler); correct musnad convention",
        "duplicate_of": None,
    },
    {
        "book": "مختصر صحيح مسلم للمنذري ت الألباني",
        "session": 7,
        "status": "gate_abort",
        "models": "opus + command_a",
        "verdict": "VERIFIED",
        "author_name": "عبد العظيم بن عبد القوي بن عبد الله، أبو محمد، زكي الدين المنذري",
        "author_correct": True,
        "author_confidence_opus": 0.99,
        "death_date": 656,
        "death_source": "pass-through",
        "genre": "mukhtasar",
        "genre_correct": True,
        "genre_confidence_opus": 0.97,
        "is_multi_layer": True,
        "ml_correct": False,
        "ml_disagreement": True,
        "science_scope": ["hadith"],
        "trust_tier": None,
        "trust_score": None,
        "consensus_agreed": True,
        "key_issues": "Tahqiq-as-layer bias instance #5: Opus ML=true (wrong), CA=false; cross-edition consistent with Errata §9",
        "duplicate_of": None,
    },
    {
        "book": "من أحاديث سفيان الثوري - رواية السري بن يحيى - جوامع الكلم",
        "session": 7,
        "status": "success",
        "models": "opus + command_a",
        "verdict": "PLAUSIBLE",
        "author_name": "السرى بن يحيى بن إياس بن حرملة بن إياس الشيبانى المحلمى",
        "author_correct": True,
        "author_confidence_opus": 0.85,
        "death_date": 167,
        "death_source": "pass-through",
        "genre": "hadith_collection",
        "genre_correct": True,
        "genre_confidence_opus": 0.92,
        "is_multi_layer": False,
        "ml_correct": True,
        "ml_disagreement": False,
        "science_scope": ["hadith"],
        "trust_tier": "verified",
        "trust_score": 0.6925,
        "consensus_agreed": False,
        "key_issues": "Consensus disagreed (name format only); author=السري (transmitter) not سفيان (narrator)",
        "duplicate_of": None,
    },
]

# ══════════════════════════════════════════════════════════════
# Compute statistics
# ══════════════════════════════════════════════════════════════

assert len(verdicts) == 76, f"Expected 76 verdicts, got {len(verdicts)}"

unique_books = set(v["book"] for v in verdicts)

# Counts by verdict
counts_by_verdict = {}
for v in verdicts:
    counts_by_verdict[v["verdict"]] = counts_by_verdict.get(v["verdict"], 0) + 1

# Counts by session
counts_by_session = {}
for v in verdicts:
    s = v["session"]
    if s not in counts_by_session:
        counts_by_session[s] = {"total": 0, "VERIFIED": 0, "PLAUSIBLE": 0}
    counts_by_session[s]["total"] += 1
    counts_by_session[s][v["verdict"]] += 1

# Counts by genre
counts_by_genre = {}
for v in verdicts:
    g = v["genre"]
    if g not in counts_by_genre:
        counts_by_genre[g] = {"total": 0, "VERIFIED": 0, "PLAUSIBLE": 0}
    counts_by_genre[g]["total"] += 1
    counts_by_genre[g][v["verdict"]] += 1

# Counts by status
counts_by_status = {}
for v in verdicts:
    st = v["status"]
    if st not in counts_by_status:
        counts_by_status[st] = {"total": 0, "VERIFIED": 0, "PLAUSIBLE": 0}
    counts_by_status[st]["total"] += 1
    counts_by_status[st][v["verdict"]] += 1

# Author confidence stats
author_confs = [v["author_confidence_opus"] for v in verdicts]
author_conf_stats = {
    "min": min(author_confs),
    "max": max(author_confs),
    "mean": round(statistics.mean(author_confs), 4),
    "median": round(statistics.median(author_confs), 4),
}

# Genre confidence stats
genre_confs = [v["genre_confidence_opus"] for v in verdicts]
genre_conf_stats = {
    "min": min(genre_confs),
    "max": max(genre_confs),
    "mean": round(statistics.mean(genre_confs), 4),
    "median": round(statistics.median(genre_confs), 4),
}

# Trust tier distribution (success books only)
trust_dist = {}
for v in verdicts:
    if v["trust_tier"] is not None:
        t = v["trust_tier"]
        trust_dist[t] = trust_dist.get(t, 0) + 1

# ML disagreement count
ml_disagree = sum(1 for v in verdicts if v["ml_disagreement"])

# Death source distribution
death_source_dist = {}
for v in verdicts:
    ds = v["death_source"]
    death_source_dist[ds] = death_source_dist.get(ds, 0) + 1

stats = {
    "total_verdicts": 76,
    "unique_books": len(unique_books),
    "duplicate_verdicts": 76 - len(unique_books),
    "counts_by_verdict": counts_by_verdict,
    "counts_by_session": {str(k): v for k, v in sorted(counts_by_session.items())},
    "counts_by_genre": dict(sorted(counts_by_genre.items(), key=lambda x: -x[1]["total"])),
    "counts_by_status": counts_by_status,
    "author_confidence_opus": author_conf_stats,
    "genre_confidence_opus": genre_conf_stats,
    "trust_tier_distribution": trust_dist,
    "ml_disagreement_count": ml_disagree,
    "death_source_distribution": death_source_dist,
}

output = {"verdicts": verdicts, "_statistics": stats}

out_path = Path("phase_c_collection/PHASE_C_ALL_VERDICTS.json")
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Written {len(verdicts)} verdicts to {out_path}")
print(f"Unique books: {len(unique_books)}")
print(f"Verdicts: {counts_by_verdict}")
print(f"Author conf: {author_conf_stats}")
print(f"Genre conf: {genre_conf_stats}")
print(f"Trust dist: {trust_dist}")
print(f"ML disagreements: {ml_disagree}")
print(f"Death sources: {death_source_dist}")
