#!/usr/bin/env python3
"""Review recursive-improve proposals before application.

Reads ri's eval/action_plan.md (generated by `recursive-improve eval`),
parses proposed fixes, and presents them for architect review.  Approved
fixes are applied on a dedicated git branch.  Rejected fixes are logged.

This script enforces KR's principle: ri proposes, human approves.

Usage:
    python scripts/ri_review.py                        # review pending proposals
    python scripts/ri_review.py --plan eval/action_plan.md  # specify plan file
    python scripts/ri_review.py --auto-reject-content  # auto-reject content prompt changes
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_root))

# Patterns that indicate content-affecting changes (auto-reject)
_CONTENT_PROMPT_PATTERNS = [
    r"engines/.*/prompts/",
    r"genre.*classif",
    r"author.*identif",
    r"science.*scope",
    r"school.*attrib",
    r"madhab",
    r"consensus.*prompt",
]


def parse_action_plan(plan_path: Path) -> list[dict[str, str]]:
    """Parse ri's action_plan.md into a list of proposed fixes.

    Returns list of dicts with keys: title, category, severity,
    description, file_path, diff.
    """
    if not plan_path.exists():
        return []

    text = plan_path.read_text(encoding="utf-8")
    fixes: list[dict[str, str]] = []
    current: dict[str, str] = {}

    for line in text.split("\n"):
        # Section headers like "### Fix 1: Improve schema directive"
        if line.startswith("### "):
            if current:
                fixes.append(current)
            current = {"title": line.lstrip("# ").strip()}
        elif line.startswith("- **Category"):
            current["category"] = line.split(":", 1)[-1].strip().rstrip("*")
        elif line.startswith("- **Severity"):
            current["severity"] = line.split(":", 1)[-1].strip().rstrip("*")
        elif line.startswith("- **File"):
            current["file_path"] = line.split(":", 1)[-1].strip().rstrip("*")
        elif line.startswith("```"):
            if "diff" not in current:
                current["diff"] = ""
        elif "diff" in current and not line.startswith("```"):
            current["diff"] = current.get("diff", "") + line + "\n"
        elif current and "title" in current:
            current["description"] = (
                current.get("description", "") + line + "\n"
            )

    if current:
        fixes.append(current)

    return fixes


def is_content_affecting(fix: dict[str, str]) -> bool:
    """Check if a proposed fix affects content classification prompts."""
    file_path = fix.get("file_path", "")
    description = fix.get("description", "")
    combined = f"{file_path} {description}".lower()

    return any(
        re.search(pattern, combined, re.IGNORECASE)
        for pattern in _CONTENT_PROMPT_PATTERNS
    )


def review_fixes(
    fixes: list[dict[str, str]],
    auto_reject_content: bool = True,
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Classify fixes as approved or rejected.

    Content-affecting fixes are auto-rejected when auto_reject_content
    is True (the default — enforces KR safety invariant).
    """
    approved: list[dict[str, str]] = []
    rejected: list[dict[str, str]] = []

    for fix in fixes:
        if auto_reject_content and is_content_affecting(fix):
            fix["rejection_reason"] = (
                "Auto-rejected: affects content classification prompts "
                "(genre/author/science/school). Per KR safety invariant, "
                "these changes require manual review, not ri automation."
            )
            rejected.append(fix)
        else:
            # Non-content fixes are approved for application
            approved.append(fix)

    return approved, rejected


def save_decisions(
    approved: list[dict[str, str]],
    rejected: list[dict[str, str]],
    output_path: Path,
) -> None:
    """Save review decisions to a JSON log."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    decisions = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "approved_count": len(approved),
        "rejected_count": len(rejected),
        "approved": approved,
        "rejected": rejected,
    }
    output_path.write_text(
        json.dumps(decisions, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Review recursive-improve proposals for KR safety"
    )
    parser.add_argument(
        "--plan",
        type=Path,
        default=_root / "eval" / "action_plan.md",
        help="Path to ri action plan (default: eval/action_plan.md)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path for decision log (default: eval/ri_decisions_{timestamp}.json)",
    )
    parser.add_argument(
        "--auto-reject-content",
        action="store_true",
        default=True,
        help="Auto-reject fixes that affect content classification (default: True)",
    )
    args = parser.parse_args(argv)

    if args.output is None:
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output = _root / "eval" / f"ri_decisions_{ts}.json"

    # Parse
    fixes = parse_action_plan(args.plan)
    if not fixes:
        print("No proposals found in action plan.")
        return 0

    print(f"Found {len(fixes)} proposals in {args.plan}")
    print()

    # Review
    approved, rejected = review_fixes(fixes, args.auto_reject_content)

    # Report
    for fix in rejected:
        print(f"  REJECTED: {fix.get('title', 'untitled')}")
        print(f"    Reason: {fix.get('rejection_reason', 'manual rejection')}")
    for fix in approved:
        print(f"  APPROVED: {fix.get('title', 'untitled')}")
        print(f"    File: {fix.get('file_path', 'unknown')}")

    print()
    print(f"Approved: {len(approved)}, Rejected: {len(rejected)}")

    # Save
    save_decisions(approved, rejected, args.output)
    print(f"Decisions saved to: {args.output}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
